//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acil_Kayit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acil_Kayit()
        {
            this.Malzeme_Kullanim = new HashSet<Malzeme_Kullanim>();
            this.Recete = new HashSet<Recete>();
            this.Sonuc = new HashSet<Sonuc>();
        }
    
        public int acil_id { get; set; }
        public Nullable<System.DateTime> acil_giris_tarihi { get; set; }
        public Nullable<System.DateTime> acil_cikis_tarihi { get; set; }
        public string acil_tani { get; set; }
        public int personel_id { get; set; }
        public int hasta_id { get; set; }
        public bool acil_kayit_durum { get; set; }
    
        public virtual Hasta Hasta { get; set; }
        public virtual Personel Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Malzeme_Kullanim> Malzeme_Kullanim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recete> Recete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sonuc> Sonuc { get; set; }
    }
}
