//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bütce
    {
        public int bütce_id { get; set; }
        public decimal bütce_tutar { get; set; }
        public string bütce_kategori { get; set; }
        public bool bütce_tipi { get; set; }
        public Nullable<System.DateTime> bütce_tarihi { get; set; }
    }
}
