//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hasta()
        {
            this.Acil_Kayit = new HashSet<Acil_Kayit>();
            this.Randevu = new HashSet<Randevu>();
        }
    
        public int hasta_id { get; set; }
        public string hasta_ad { get; set; }
        public string hasta_soyad { get; set; }
        public string hasta_tcno { get; set; }
        public bool hasta_cinsiyet { get; set; }
        public System.DateTime hasta_dogum_tarihi { get; set; }
        public string hasta_telefon { get; set; }
        public Nullable<int> adres_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acil_Kayit> Acil_Kayit { get; set; }
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
    }
}
