//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilac_Recete
    {
        public int ilac_recete_id { get; set; }
        public int recete_id { get; set; }
        public Nullable<int> ilac_id { get; set; }
    
        public virtual Ilac Ilac { get; set; }
        public virtual Recete Recete { get; set; }
    }
}
