//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme_Alim
    {
        public int alim_id { get; set; }
        public string alim_firma { get; set; }
        public int alim_adet { get; set; }
        public decimal alim_fiyat { get; set; }
        public Nullable<System.DateTime> alim_tarihi { get; set; }
        public Nullable<int> malzeme_id { get; set; }
    
        public virtual Malzeme_Stok Malzeme_Stok { get; set; }
    }
}
