//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzeme_Kullanim
    {
        public int kullanim_id { get; set; }
        public Nullable<int> kullanim_adet { get; set; }
        public Nullable<System.DateTime> kullanim_tarihi { get; set; }
        public Nullable<int> malzeme_id { get; set; }
        public Nullable<int> acil_id { get; set; }
        public Nullable<int> randevu_id { get; set; }
    
        public virtual Acil_Kayit Acil_Kayit { get; set; }
        public virtual Malzeme_Stok Malzeme_Stok { get; set; }
        public virtual Randevu Randevu { get; set; }
    }
}
