//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Acil_Kayit = new HashSet<Acil_Kayit>();
            this.Randevu = new HashSet<Randevu>();
        }
    
        public int personel_id { get; set; }
        public string personel_ad { get; set; }
        public string personel_soyad { get; set; }
        public string personel_tcno { get; set; }
        public bool personel_cinsiyet { get; set; }
        public System.DateTime personel_dogum_tarihi { get; set; }
        public string personel_telefon { get; set; }
        public Nullable<System.DateTime> personel_giris_tarihi { get; set; }
        public Nullable<int> adres_id { get; set; }
        public Nullable<int> meslek_id { get; set; }
        public Nullable<int> departman_id { get; set; }
        public bool personel_durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acil_Kayit> Acil_Kayit { get; set; }
        public virtual Adres Adres { get; set; }
        public virtual Departman Departman { get; set; }
        public virtual Meslek Meslek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
    }
}
