//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Randevu()
        {
            this.Malzeme_Kullanim = new HashSet<Malzeme_Kullanim>();
            this.Recete = new HashSet<Recete>();
            this.Sonuc = new HashSet<Sonuc>();
        }
    
        public int randevu_id { get; set; }
        public System.DateTime randevu_tarih { get; set; }
        public Nullable<int> hasta_id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<int> departman_id { get; set; }
        public bool randevu_durum { get; set; }
    
        public virtual Departman Departman { get; set; }
        public virtual Hasta Hasta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Malzeme_Kullanim> Malzeme_Kullanim { get; set; }
        public virtual Personel Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recete> Recete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sonuc> Sonuc { get; set; }
    }
}
