//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recete()
        {
            this.Ilac_Recete = new HashSet<Ilac_Recete>();
        }
    
        public int recete_id { get; set; }
        public System.DateTime recete_son_kullanim_tarihi { get; set; }
        public bool recete_durum { get; set; }
        public Nullable<int> acil_id { get; set; }
        public Nullable<int> randevu_id { get; set; }
    
        public virtual Acil_Kayit Acil_Kayit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ilac_Recete> Ilac_Recete { get; set; }
        public virtual Randevu Randevu { get; set; }
    }
}
