//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneVeritabani.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonuc
    {
        public int sonuc_id { get; set; }
        public Nullable<System.DateTime> sonuc_test_tarih { get; set; }
        public Nullable<System.DateTime> sonuc_cikis_tarih { get; set; }
        public string sonuc_aciklama { get; set; }
        public string sonuc_test_tipi { get; set; }
        public bool sonuc_durum { get; set; }
        public Nullable<int> acil_id { get; set; }
        public Nullable<int> randevu_id { get; set; }
    
        public virtual Acil_Kayit Acil_Kayit { get; set; }
        public virtual Randevu Randevu { get; set; }
    }
}
